/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apollo;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    // difference between Arrays & Array Lists
    // ArrayList has methods
    // Array does not have methods

    // TODO: create the reverseArray method with Java Arrays
    public String[] reverse(String[] arrayToReverse) {
        // Instantiate a new array that has the length of the given array
        String[] newArray = new String[arrayToReverse.length];
        // Loop through the given array in reverse, starting at the end.
        for (int i = 0; i < arrayToReverse.length; i++) {
            newArray[(arrayToReverse.length - 1) - i] = arrayToReverse[i];
        }
        return newArray;
    }

    // TODO: create reverse method with ArrayLists
    // Polymorphism -> method overloading
    public ArrayList<String> reverse(ArrayList<String> arrayToReverse) {
        ArrayList<String> newArray = new ArrayList<>();
        for (int i = arrayToReverse.size(); i >= 0; i--) {
            newArray.add(arrayToReverse.get(i));
        }
        return newArray;
    }
}
