/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apollo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    // arrange, act, assert
    @Test void someRandomTest() {
        int x = 7;
        int y = 7;
        assertEquals(x, 7);
    }
    @Test void testReverseArray(){
        // arrange
        // sut === system under test
        Library sut = new Library();
        String[] testStringArray = {"Apollo", "Hercules", "Zeus"};
        // act
        String[] resultArray = sut.reverse(testStringArray);
        // assert
        assertArrayEquals(resultArray, new String[]{"Zeus", "Hercules", "Apollo"});
        assertTrue(resultArray.length == testStringArray.length);
        assertTrue(resultArray[0].equals("Zeus"));

    }
}
